project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "PolOpT EMDB"
  repo-url: https://github.com/renatovargas/gears/
  repo-actions: [source]
  repo-branch: master
  navbar:
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Download"
        href: download.qmd
      - text: "Documentation"
        href: documentation/index.qmd
      - about.qmd
      
  sidebar:
    - title: "Documentation"
      style: "docked"
      contents:
        - section: "Methods"
          contents:
            - text: "Database peparation"
              href: documentation/methods/emissions_db_construction.qmd
            - text: "Processing code"
              href: documentation/methods/emdb_processing.qmd
          
format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true



