---
title: "About"
---

# General Information

The Agrifood Economics and Policy Division (ESA) conducts economic research and policy analysis to support the transformation to more efficient, inclusive, resilient and sustainable agrifood systems for better production, better nutrition, a better environment, and a better life, leaving no one behind. ESA provides evidence-based support to national, regional and global policy processes and initiatives related to monitoring and analysing food and agricultural policies, agribusiness and value chain development, rural transformation and poverty, food security and nutrition information and analysis, resilience, bioeconomy, and climate-smart agriculture. The division also leads the production of two FAO flagship publications: The State of Food and Agriculture (SOFA) and The State of Food Security and Nutrition in the World (SOFI).

Within ESA, the Monitoring and Analysing Food and Agricultural Policies (MAFAP) programme seeks to establish country owned and sustainable systems to monitor, analyse, and reform food and agricultural policies to enable more effective, efficient and inclusive policy frameworks in 8 developing and emerging economies. MAFAP works with government institutions, research organizations and other partners to create sustainable policy monitoring systems and carry out a consistent set of policy and public expenditure analyses across a wide range of agricultural value chains. MAFAP analyses are used to inform targeted food and agricultural policy reforms that will result in a more conducive environment for agricultural investment and productivity growth, especially for smallholder farmers. As such, MAFAP supports most of FAO strategic objectives, and in particular those of enabling inclusive and efficient agricultural and food systems and helping eliminate hunger, food insecurity and malnutrition.  

A policy optimization modelling tool (that combines a recursive-dynamic computable general equilibrium model and multi-criteria decision-making techniques) is being used by the MAFAP programme team to develop and analyse scenarios where the public budget for the food and agriculture sector can be optimally re-allocated across different support measures (input subsidies, extension services, investments in different types of rural infrastructures, R&D, and so forth) and subsectors/commodities, aiming at improving on one or a combination of inclusive agricultural transformation (IAT) objectives such as: maximizing agrifood GDP, maximizing the number of off- farm jobs created in rural areas (vis-à-vis the number of on-farm jobs), and minimizing rural poverty. Most recently, the objective of minimizing the cost of the least-cost healthy diet was added to the tool. Next extensions to the tool comprise adding other objectives, notably the minimization of greenhouse gas (GHGs) emissions that are generated as a result of public expenditures in food and agriculture.

# Disclaimer

The designations employed and the presentation of information on this website do not imply the expression of any opinion whatsoever on the part of FAO concerning the legal or development status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers or boundaries. The mention of specific companies or products of manufacturers, whether or not these have been patented, does not imply that these have been endorsed or recommended by FAO in preference to others of a similar nature that are not mentioned.

Information on this site is provided on an "as is" and "as available" basis. FAO makes every effort to ensure, but does not guarantee, the accuracy, completeness or authenticity of the information on this website. FAO reserves the right to alter, limit or discontinue any part of this service at its discretion. Under no circumstances shall FAO be liable for any loss, damage, liability or expense suffered that is claimed to result from the use of information posted on this site, including without limitation, any fault, error, omission, interruption or delay.

Hyperlinks to non-FAO websites do not imply any official endorsement of or responsibility on the part of FAO for the opinions, ideas, data or products presented at these locations, or guarantee the validity of the information provided. The sole purpose of links to non-FAO sites is to indicate further information available on related topics. The information is provided on the basis that users accessing the platform assume responsibility for assessing its relevance, accuracy and suitability for application.

No part of these Terms and Conditions shall constitute or be interpreted as a waiver of the privileges and immunities of FAO.
