---
title: "Customize"
---

The tool below allows you to map data for a single country and one year to your Social Accounting Matrix or Input-Output table structure. It requires you to fill out the Excel file download with your data, without changing column names on either sheet or the data under the ISIC Detail column in the "Equivalence" sheet. The example is tailored to Nigeria's 2018 Social Accounting Matrix, which you can [download here](https://github.com/renatovargas/emdb/raw/refs/heads/master/emdb/data/sam/nga/SAM-Nigeria-2018.xlsx) for reference. 

The first sheet requires you to enter a column of your entire accounting structure in order. This includes all accounts; even those that are not related to emissions data. This will make sure that the download matches your structure. The second sheet requires you to provide equivalences from your economic activities to the sectors and subsectors in the database.

The resulting download will have as many columns as your own structure and in the order you specify them in the "User Structure" sheet instead of ISIC sectors. The data will be filled out in the appropriate columns according to your mapping in the "Equivalence" sheet and it will feature a series of columns beginning with "9999" after the `Total` column. This is as far as we can take you. You can then distribute those columns among your own structure columns using your choice of input, output, endowment shares, as allowed by your data. Make sure to distribute excluding those sectors that are already populated within your data structure.

<a class="btn btn-primary btn-sm btn-center" href="https://github.com/renatovargas/emdb/raw/refs/heads/master/emdb/data/sam/nga/map-emdb.xlsx" download="map-emdb.xlsx"> Example Equivalence File</a>

Upload the equivalence file above adapted to your own structure using the tool[^1] (depending on your connection, it might take a few seconds to load) and download your customized file.

::: {.center}
<iframe src="https://renatovargas.shinyapps.io/map_emdb/" 
        width="100%" 
        height="600px" 
        style="border:none;">
</iframe>
:::

[^1]: The R logic behind the tool is simple data manipulation and the interested reader can [understand the code here](documentation/methods/querying_the_database.qmd) and adapt it to their own needs.